title: Michael Moreno # your name (or website title) here
logo: "/images/profilepic.png?raw=true" # your photo (or logo) here
description: > 'Hi, my names Michael and I am a recent grad from CSU Sacramento with a BA in Economics.
 These EDA projects showcase my growth since I began in May 2021 to current date.
 You will find cleaning done in SQL and R files and the visuals were created 
 with R packages, Tabluea and Power BI.'
 
 <a href="www.linkedin.com/in/michaelmoreno17">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
