title: Michael Moreno # your name (or website title) here
logo: "/images/profilepic.png?raw=true" # your photo (or logo) here
description: > 
 Hi, my names Michael and I am a recent grad from CSU Sacramento with a BA in Economics.
 Below are my Exploritory Data Analysis projects which showcase my growth since I began in May 2021 to the present.
 You will find data cleansing done in SQL and R files and the visuals were created 
 with R packages, Tableau and Power BI.
 <br> <br>
 
 <a href="https://www.linkedin.com/in/michaelmoreno17/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
